from sqlalchemy import create_engine, text
from config import DATABASE_PUBLIC_URL

engine = create_engine(DATABASE_PUBLIC_URL)

def rename_columns():
    actions = [
        'ALTER TABLE projects RENAME COLUMN "projectgrantname" TO project_grant_name;',
        'ALTER TABLE projects RENAME COLUMN "leadresearcher" TO lead_researcher;',
        'ALTER TABLE projects RENAME COLUMN "leadresearchinstitute" TO lead_research_institute;',
        'ALTER TABLE projects RENAME COLUMN "grantnumbers" TO grant_numbers;',
        'ALTER TABLE projects RENAME COLUMN "projectgrantstartdate" TO project_grant_start_date;',
        'ALTER TABLE projects RENAME COLUMN "projectgrantenddate" TO project_grant_end_date;',
        'ALTER TABLE projects RENAME COLUMN "projectgrantscope" TO project_grant_scope;',
    ]
    return actions

def auto_increment():
    actions = ['ALTER TABLE publications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;']
    return actions

def start_from_100():
    actions = ['ALTER TABLE publications ALTER COLUMN id RESTART WITH 100;']
    return actions

def fix_all_other_auto_inc():
    actions = ['ALTER TABLE project_datasets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;',
    'ALTER TABLE project_datasets ALTER COLUMN id RESTART WITH 100;',
    'ALTER TABLE teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;',
    'ALTER TABLE teams ALTER COLUMN id RESTART WITH 100;',
    'ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;',
    'ALTER TABLE users ALTER COLUMN id RESTART WITH 100;',
    'ALTER TABLE datasets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;',
    'ALTER TABLE datasets ALTER COLUMN id RESTART WITH 100;',
    'ALTER TABLE projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;',
    'ALTER TABLE projects ALTER COLUMN id RESTART WITH 100;',
    'ALTER TABLE cancer_term_mappings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;',
    'ALTER TABLE cancer_term_mappings ALTER COLUMN id RESTART WITH 100;',
    'ALTER TABLE snomed_filters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;',
    'ALTER TABLE snomed_filters ALTER COLUMN id RESTART WITH 100;'
               ]
    return actions

with engine.connect() as conn:
    # pick the correct command to alter the database
    for cmd in fix_all_other_auto_inc():
        conn.execute(text(cmd))
    conn.commit()

print("Remote database columns updated successfully.")